sudo: required
services:
  - docker

before_install:
  - docker build -t opt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run opt/react-test npm test -- --coverage

after_success:
  # - docker build -t mikecallari/multi-client -f ./client/Dockerfile ./client
  # - docker build -t mikecallari/multi-nginx -f ./nginx/Dockerfile ./nginx
  # - docker build -t mikecallari/multi-server -f ./server/Dockerfile ./server
  # - docker build -t mikecallari/multi-worker -f ./worker/Dockerfile ./worker
  # # Log in to docker CLI
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # # Push to docker hub.
  # - docker push mikecallari/multi-client
  # - docker push mikecallari/multi-nginx
  # - docker push mikecallari/multi-server
  # - docker push mikecallari/multi-worker
  # Install aws cli w/o sudo
  - pip install --user awscli
  # Put aws in the path
  - export PATH=$PATH:$HOME/.local/bin
  # Log into AWS cli
  - eval $(aws ecr get-login --no-include-email --region us-east-1)
  # Build images
  - docker build -t opt/multi-client -f ./client/Dockerfile ./client
  - docker build -t opt/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t opt/multi-server -f ./server/Dockerfile ./server
  - docker build -t opt/multi-worker -f ./worker/Dockerfile ./worker
  - docker tag opt/multi-client:latest 669386438505.dkr.ecr.us-east-1.amazonaws.com/opt/multi-client:latest
  - docker tag opt/multi-nginx:latest 669386438505.dkr.ecr.us-east-1.amazonaws.com/opt/multi-nginx:latest
  - docker tag opt/multi-server:latest 669386438505.dkr.ecr.us-east-1.amazonaws.com/opt/multi-server:latest
  - docker tag opt/multi-worker:latest 669386438505.dkr.ecr.us-east-1.amazonaws.com/opt/multi-worker:latest
  # Push to ACS
  - docker push 669386438505.dkr.ecr.us-east-1.amazonaws.com/opt/multi-client
  - docker push 669386438505.dkr.ecr.us-east-1.amazonaws.com/opt/multi-nginx
  - docker push 669386438505.dkr.ecr.us-east-1.amazonaws.com/opt/multi-server
  - docker push 669386438505.dkr.ecr.us-east-1.amazonaws.com/opt/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-east-1-669386438505
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY

