sudo: required
services:
  - docker

before_install:
  - docker build -t mikecallari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mikecallari/react-test npm test -- --coverage

after_success:
  - docker build -t mikecallari/multi-client -f ./client/Dockerfile ./client
  - docker build -t mikecallari/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t mikecallari/multi-server -f ./server/Dockerfile ./server
  - docker build -t mikecallari/multi-worker -f ./worker/Dockerfile ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub.
  - docker push mikecallari/multi-client
  - docker push mikecallari/multi-nginx
  - docker push mikecallari/multi-server
  - docker push mikecallari/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MiltiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-669386438505
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

